# Generated by Django 3.0.8 on 2020-08-18 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vlogsite', '0002_auto_20200801_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comt', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('belond', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='vlogsite.vlogText')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='First', to='vlogsite.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
