# Generated by Django 3.0.8 on 2020-10-12 21:07

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vlogsite', '0007_auto_20201011_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlogtext',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
